### PR TITLE
Page source

### PR DESCRIPTION
**Pull request by ylavoie**

### CODE REVIEW

**Comment by ehuelsmann** [comment]
Why?

**Comment by ehuelsmann** [comment]
I would argue that the documentation of the api is wrong here, not the implementation: all layers have returned the content from day 1

**Comment by ylavoie** [comment]
I would argue that screenshot and page_source should be similar. We either print on both in the driver or don't.

**Comment by ehuelsmann** [comment]
Ok. I can go with that, but why update the version number by 2?

**Comment by ylavoie** [comment]
Because there was another before that which was bearing version 6. Fixed.

**Pull request merged**
